#!/bin/bash

# Script to add new files to Xcode project
# Run this from the Beam/ directory

echo "📦 Adding new cryptography files to Xcode project..."

echo ""
echo "⚠️  MANUAL STEPS REQUIRED:"
echo ""
echo "1. Open Beam.xcodeproj in Xcode"
echo ""
echo "2. Add these NEW files to the project:"
echo "   Services/"
echo "   ├── CryptoService.swift          ✨ NEW"
echo "   ├── KeychainService.swift        ✨ NEW"
echo "   "
echo "   Models/"
echo "   ├── ContactCard.swift            ✨ NEW"
echo "   ├── SessionState.swift           ✨ NEW"
echo "   ├── EncryptedMessage.swift       ✨ NEW"
echo ""
echo "3. How to add files:"
echo "   a. Right-click 'Services' folder in Xcode"
echo "   b. Select 'Add Files to Beam...'"
echo "   c. Navigate to Beam/Beam/Services/"
echo "   d. Select CryptoService.swift and KeychainService.swift"
echo "   e. Ensure 'Add to targets: Beam' is CHECKED ✓"
echo "   f. Click 'Add'"
echo ""
echo "   g. Right-click 'Models' folder in Xcode"
echo "   h. Select 'Add Files to Beam...'"
echo "   i. Navigate to Beam/Beam/Models/"
echo "   j. Select ContactCard.swift, SessionState.swift, EncryptedMessage.swift"
echo "   k. Ensure 'Add to targets: Beam' is CHECKED ✓"
echo "   l. Click 'Add'"
echo ""
echo "4. Build the project (⌘B)"
echo ""
echo "📄 Files are located at:"
find Beam -name "CryptoService.swift" -o -name "KeychainService.swift" -o -name "ContactCard.swift" -o -name "SessionState.swift" -o -name "EncryptedMessage.swift" 2>/dev/null | sort
echo ""
echo "✅ After adding files, run: xcodebuild -scheme Beam -destination 'platform=macOS' build"
